## thanks to https://dzone.com/articles/continuous-integration-windows
## with some adjustments and exported yaml-settings

version: '{build}'
os: Windows Server 2012
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
      $env:Path +=";C:\maven\apache-maven-3.5.2\bin;%JAVA_HOME%\bin"
build_script:
  - cmd: mvn clean package --batch-mode -DskipTest
test_script:
  - cmd: mvn clean install --batch-mode

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9

matrix:
  fast_finish: true
